openapi: 3.0.0
servers: []
info:
  description: |
    This is the specification of the PROMINENCE REST API.
    This is still considered a work in progress, so things could change or break with every update.
  version: 1.0.0
  title: PROMINENCE REST API 
  
tags:
  - name: jobs
    description: API endpoint for managing jobs
  - name: workflows
    description: API endpoint for managing workflows
  - name: data
    description: API endpoint for managing data
    
paths:
  /jobs:
    post:
      tags:
        - jobs
      summary: Create a job
      responses:
        '201':
          description: Success       
        '400':
          description: Invalid job description    
        '401':
          description: Authentication failure
    get:
      tags:
        - jobs
      summary: List jobs
      description: Returns a list of jobs
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '401':
          description: Authentication failure
  '/jobs/{id}':
    get:
      tags:
        - jobs
      summary: Describe a job
      description: Describe a job
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid job ID provided                
        '401':
          description: Authentication failure
        '404':
          description: Job not found
    delete:
      tags:
        - jobs
      summary: Delete a job
      parameters:
        - name: id
          in: path
          description: Job id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success     
        '400':
          description: Invalid job ID supplied
        '401':
          description: Authentication failure   
        '403':
          description: Not authorised to kill this job     
        '404':
          description: Job not found
  '/jobs/{id}/stdout':
    get:
      tags:
        - jobs
      summary: Get standard output from a job
      description: Get standard output from a job
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Job does not exist
        '401':
          description: Authentication failure
        '403':
          description: Not authorised to access this job       
        '404':
          description: Standard output does not exist
  '/jobs/{id}/stderr':
    get:
      tags:
        - jobs
      summary: Get standard error from a job
      description: Get standard error from a job
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Job does not exist
        '401':
          description: Authentication failure
        '403':
          description: Not authorised to access this job       
        '404':
          description: Standard output does not exist
  '/workflows':
    post:
      tags:
        - workflows
      summary: Create a workflow
      description: Create a workflow
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64      
      responses:
        default:
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
        description: Created user object
        required: true
    get:
      tags:
        - workflows
      summary: List workflows
      parameters:
        - name: username
          in: path
          description: The name that needs to be fetched. Use user1 for testing.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '401':
          description: Authentication failure   
  '/workflows/{id}':
    get:
      tags:
        - workflows
      summary: Describe a workflow
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64            
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Invalid workflow ID provided                
        '401':
          description: Authentication failure
        '404':
          description: Workflow not found
    delete:
      tags:
        - workflows
      summary: Delete a workflow
      parameters:
        - name: id
          in: path
          description: Workflow id to delete
          required: true
          schema:
            type: integer
            format: int64               
      responses:
        '200':
          description: Success     
        '400':
          description: Invalid workflow ID supplied
        '401':
          description: Authentication failure   
        '403':
          description: Not authorised to kill this workflow   
        '404':
          description: Workflow not found
  '/data':
    post:
      tags:
        - data
      summary: Obtain a presigned URL for uploading data
      responses:
        '401':
          description: Authentication failure      
        '405':
          description: Invalid input
    get:
      tags:
        - data
      summary: List files in object storage
      description: List files in object storage
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '401':
          description: Authentication failure
        '403':
          description: Not authorised to access this path 
    delete:
      tags:
        - data
      summary: Delete file in object storage
      parameters:
        - name: object name
          in: path
          description: Object name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success     
        '400':
          description: Invalid object name supplied
        '401':
          description: Authentication failure   
        '403':
          description: Not authorised to delete this object   
        '404':
          description: Object not found
          
externalDocs:
  description: Find out more about PROMINENCE
  url: 'https://prominence-eosc.github.io/docs'
  
components:
  schemas:
    Job:
      type: object
      properties:
        name:
          type: string
          description: Job name
        resources:
          type: Resources
          description: Requested resources
        tasks:
          type: string
          description: List of tasks      
      xml:
        name: Job 
    Resources:
      type: object
      properties:
        cpus:
          type: integer
          format: int32
          description: Requested number of CPUs
        memory:
          type: integer
          format: int32
          description: Requested memory in GB
        disk:
          type: integer
          format: int32
          description: Requested local disk in GB
        nodes:
          type: string
          format: int32
          description: Requested number of nodes
      xml:
        name: Resources
    Task:
      type: object
      properties:
        image:
          type: string
          description: Container image
        runtime:
          type: string
          description: Container runtime
          enum:
            - singularity
            - udocker
        cmd:
          type: string
          description: Command to execute
        workdir:
          type: string
          description: Current working directory
        type:
          type: string
          description: Task type
          enum:
            - basic
            - openmpi
            - mpich
            - intelmpi
      xml:
        name: Task
